//
//  BraintreeErrorTypes.swift
//  expo-braintree
//
//  Error type definitions
//

import Foundation

enum EXCEPTION_TYPES: String {
  case SWIFT_EXCEPTION = "ReactNativeExpoBraintree:`SwiftException"
  case USER_CANCEL_EXCEPTION = "ReactNativeExpoBraintree:`UserCancelException"
  case TOKENIZE_EXCEPTION = "ReactNativeExpoBraintree:`TokenizeException"
  case PAYPAL_DISABLED_IN_CONFIGURATION =
    "ReactNativeExpoBraintree:`Paypal disabled in configuration"
}

enum ERROR_TYPES: String {
  case API_CLIENT_INITIALIZATION_ERROR = "API_CLIENT_INITIALIZATION_ERROR"
  case TOKENIZE_VAULT_PAYMENT_ERROR = "TOKENIZE_VAULT_PAYMENT_ERROR"
  case USER_CANCEL_TRANSACTION_ERROR = "USER_CANCEL_TRANSACTION_ERROR"
  case PAYPAL_DISABLED_IN_CONFIGURATION_ERROR = "PAYPAL_DISABLED_IN_CONFIGURATION_ERROR"
  case DATA_COLLECTOR_ERROR = "DATA_COLLECTOR_ERROR"
  case CARD_TOKENIZATION_ERROR = "CARD_TOKENIZATION_ERROR"
  case APPLE_PAY_NOT_AVAILABLE = "APPLE_PAY_NOT_AVAILABLE"
  case APPLE_PAY_TOKENIZATION_ERROR = "APPLE_PAY_TOKENIZATION_ERROR"
  case THREE_D_SECURE_NOT_ABLE_TO_SHIFT_LIABILITY = "THREE_D_SECURE_NOT_ABLE_TO_SHIFT_LIABILITY"
  case THREE_D_SECURE_LIABILITY_NOT_SHIFTED = "THREE_D_SECURE_LIABILITY_NOT_SHIFTED"
  case THREE_D_SECURE_VERIFICATION_FAILED = "THREE_D_SECURE_VERIFICATION_FAILED"
  case THREE_D_SECURE_AUTHENTICATION_FAILED = "THREE_D_SECURE_AUTHENTICATION_FAILED"
}
